const actionTypes = {
  IS_DATA: 'IS_DATA',
  Data_USER: 'Data_USER',
  DATA_PENDIDIKAN: 'DATA_PENDIDIKAN',
  SUCCESS_CREATE_PERSONAL: 'SUCCESS_CREATE_PERSONAL',
  SUCCESS_CREATE_PENDIDIKAN: 'SUCCESS_CREATE_PENDIDIKAN',
  DATA_KERJA: 'DATA_KERJA',
  DATA_KEMAMPUAN: 'DATA_KEMAMPUAN',
};

export default actionTypes;